// src/services/prompts.js
// This file defines system and user prompts for various AI-driven career services.

// export const SYSTEM_PROMPTS = {
//   resumeAdvisor: "You are an expert career advisor and resume reviewer with 15+ years of experience in recruitment and career development. Provide detailed, actionable feedback to help job seekers improve their resumes.",
//   jobDescriptionAnalyzer: "You are an expert recruiter and career advisor who helps job seekers understand job postings and improve their application success rate.",
//   careerStrategist: "You are a senior career strategist and executive coach with expertise in career development, market trends, and professional growth strategies.",
//   interviewCoach: "You are an expert interview coach who helps candidates prepare for job interviews by predicting likely questions and providing guidance.",
//   careerAssistant: "You are an expert AI career assistant helping job seekers with their career development and job search. You have access to the user\\\"s profile and job application history.",
// };

// export const USER_PROMPTS = {
//   analyzeResume: (resumeText, targetRole) => `\nAs an expert career advisor and resume reviewer, analyze the following resume and provide comprehensive feedback.\n\n${targetRole ? `Target Role: ${targetRole}` : ""}\n\nResume Content:\n${resumeText}\n\nPlease provide a detailed analysis including:\n\n1. **Overall Assessment** (score out of 10)\n2. **Strengths** (what\\\"s working well)\n3. **Areas for Improvement** (specific suggestions)\n4. **Missing Elements** (what should be added)\n5. **Formatting & Structure** (layout and organization feedback)\n6. **Keywords & ATS Optimization** (for applicant tracking systems)\n7. **Industry-Specific Recommendations** (if target role is provided)\n8. **Action Items** (prioritized list of improvements)\n\nFormat your response as a structured JSON object with these sections.\nBe specific, actionable, and constructive in your feedback.\n`,

//   analyzeJobDescription: (jobDescription) => `\nAnalyze the following job description and extract key information to help job seekers understand the role better.\n\nJob Description:\n${jobDescription}\n\nPlease provide a comprehensive analysis including:\n\n1. **Role Summary** (brief overview)\n2. **Key Responsibilities** (main duties and tasks)\n3. **Required Skills** (must-have technical and soft skills)\n4. **Preferred Qualifications** (nice-to-have skills)\n5. **Experience Level** (entry, mid, senior level)\n6. **Company Culture Indicators** (what the posting reveals about company culture)\n7. **Salary Range Estimate** (if not mentioned, provide market estimate)\n8. **Application Tips** (how to tailor application for this role)\n9. **Red Flags** (any concerning aspects to be aware of)\n10. **Match Score Factors** (what candidates should emphasize)\n\nFormat as a structured JSON object. Be thorough and insightful.\n`,

//   generateCareerInsights: (userProfile, jobApplications) => `\nAs a senior career strategist, analyze the following career profile and job application history to provide personalized career insights and recommendations.\n\nUser Profile:\n${JSON.stringify(userProfile, null, 2)}\n\nRecent Job Applications:\n${JSON.stringify(jobApplications.slice(0, 10), null, 2)}\n\nPlease provide comprehensive career insights including:\n\n1. **Career Trajectory Analysis** (current path and progression)\n2. **Market Position** (how competitive the candidate is)\n3. **Skill Gap Analysis** (skills to develop)\n4. **Industry Trends** (relevant to their field)\n5. **Networking Recommendations** (strategic connections to make)\n6. **Personal Branding Suggestions** (how to position themselves)\n7. **Short-term Goals** (next 6-12 months)\n8. **Long-term Strategy** (2-5 year career plan)\n9. **Application Strategy** (how to improve success rate)\n10. **Professional Development** (courses, certifications, experiences)\n\nFormat as a structured JSON object with actionable recommendations.\n`,

//   generateInterviewQuestions: (jobDescription, resumeText) => `\nBased on the following job description${resumeText ? ` and candidate resume` : ``}, generate a comprehensive list of potential interview questions the candidate should prepare for.\n\nJob Description:\n${jobDescription}\n\n${resumeText ? `Candidate Resume:\n${resumeText}` : ``}\n\nGenerate questions in these categories:\n1. **Technical Questions** (role-specific skills)\n2. **Behavioral Questions** (STAR method scenarios)\n3. **Company/Role Fit Questions** (culture and motivation)\n4. **Situational Questions** (problem-solving scenarios)\n5. **Questions About Experience** (based on resume if provided)\n\nFor each question, also provide:\n- Brief guidance on how to approach the answer\n- Key points to emphasize\n\nFormat as a structured JSON array with categories.\n`,

//   chatAssistantContext: (context) => `\nUser Context:\n${JSON.stringify(context, null, 2)}\n\nGuidelines:\n- Be helpful, encouraging, and professional\n- Provide specific, actionable advice\n- Reference the user\\\"s context when relevant\n- Ask clarifying questions when needed\n- Keep responses concise but comprehensive\n- Focus on practical career and job search advice\n- Be supportive and motivational\n\nYou can help with:\n- Resume and cover letter advice\n- Interview preparation\n- Job search strategies\n- Career planning and development\n- Skill development recommendations\n- Networking advice\n- Salary negotiation\n- Industry insights\n- Application tracking and follow-up strategies.\n`,
// };